WIP: feat: only delete halo attachment records without deleting files in object storage
halo-dev/plugin-s3 pull request #97
Opened 2023-11-09 13:42 UTC by longjuan

2023-11-09 14:09 UTC, ruibaby requested changes

2023-11-09 14:09 UTC, ruibaby commented on console/src/interface/apiTypes/Attachment.ts
可以直接安装 `@halo-dev/api-client` 包，里面包含 Attachment 类型。

2023-11-10 12:01 UTC, longjuan commented on console/src/interface/apiTypes/Attachment.ts
Done

2023-11-16 13:34 UTC, longjuan commented
/kind feature

2023-11-16 17:03 UTC, JohnNiang reviewed
/ping @halo-dev/sig-halo

2023-11-17 02:35 UTC, guqing commented on src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
> +                attachment.getMetadata().getFinalizers().remove(Constant.FINALIZER_NAME);
强删可能会导致 attachement 的关联资源没有删除，有潜在问题，是否可以通过设置一个标记的方式，然后当AttachmentReconciler 调用删除附件时检测到有标记就跳过附件文件删除？
@JohnNiang any idea?

2023-11-17 12:32 UTC, longjuan commented on src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
> +                attachment.getMetadata().getFinalizers().remove(Constant.FINALIZER_NAME);
我将在attachment对象中增加一个annotation，然后在delete方法中判断是否存在该annotation，若存在就不实际执行。/ping @halo-dev/sig-halo

2023-11-18 06:01 UTC, longjuan commented on src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
> +                attachment.getMetadata().getFinalizers().remove(Constant.FINALIZER_NAME);
df4a1822c1a9f49321f38a192efa98965cf76f99

2023-11-23 02:30 UTC, longjuan commented
/ping @halo-dev/sig-halo

2023-11-23 02:35 UTC, ruibaby reviewed
/lgtm

2023-11-23 02:42 UTC, guqing commented on src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
> +                if (objectKey == null || context.attachment().getMetadata().getAnnotations()
建议改为 MetadataUtil.nullSafeAnnotations(context.attachment()).containsKey(UNLINK_ANNO_KEY) 防止 annotations 为 null 出现 NPE

2023-11-23 02:49 UTC, JohnNiang requested changes

2023-11-23 02:49 UTC, JohnNiang commented on src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
> +    public static final String UNLINK_ANNO_KEY = "s3os.plugin.halo.run/unlink";
这里的 Annotation 值建议设置为：`s3os.plugin.halo.run/skip-remote-deletion`

2023-11-23 03:10 UTC, longjuan commented on src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
> +    public static final String UNLINK_ANNO_KEY = "s3os.plugin.halo.run/unlink";
Done

2023-11-23 03:10 UTC, longjuan commented on src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
> +                if (objectKey == null || context.attachment().getMetadata().getAnnotations()
Done

2023-11-23 03:24 UTC, guqing commented on src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
> +    public static final String UNLINK_ANNO_KEY = "s3os.plugin.halo.run/skip-remote-deletion";
UNLINK_ANNO_KEY 这个名字也顺带改一下比如 SKIP_REMOTE_DELETION_ANNO

2023-11-23 03:30 UTC, longjuan commented on src/main/java/run/halo/s3os/S3OsAttachmentHandler.java
> +    public static final String UNLINK_ANNO_KEY = "s3os.plugin.halo.run/skip-remote-deletion";
Done

2023-11-23 03:41 UTC, JohnNiang commented on src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
> +                    S3OsAttachmentHandler.SKIP_REMOTE_DELETION_ANNO, Instant.now().toString());
`SKIP_REMOTE_DELETION_ANNO` 所对应的 value 建议设置为 `"true"` or `"false"`。

另外，设置完 annotations 后，可直接调用 client::delete 方法，这样可以正常删除更新 annotations。

2023-11-23 03:43 UTC, longjuan commented on src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
> +                    S3OsAttachmentHandler.SKIP_REMOTE_DELETION_ANNO, Instant.now().toString());
意思是不需要client.update(attachment)一次，delete 方法也会更新字段？

2023-11-23 03:47 UTC, guqing commented on src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
> +                    S3OsAttachmentHandler.SKIP_REMOTE_DELETION_ANNO, Instant.now().toString());
delete 方法实际上就是更新操作，会更新上 metadata.deletionTimestamp

2023-11-23 03:49 UTC, longjuan commented on src/main/java/run/halo/s3os/S3UnlinkServiceImpl.java
> +                    S3OsAttachmentHandler.SKIP_REMOTE_DELETION_ANNO, Instant.now().toString());
Done

2023-11-23 03:50 UTC, guqing reviewed
/lgtm

2023-11-27 10:14 UTC, JohnNiang approved these changes
/approve

2023-11-27 13:49 UTC, ruibaby approved these changes

2023-11-27 13:50 UTC, merged